### ISSUE TITLE
PHP7 compatibility issue

### ISSUE THREAD

**Issue by smtalk** [piannelli/htscanner-enhanced#1]
https://forum.directadmin.com/showthread.php?t=51880

**Comment by Wouter0100** [comment]
It would be awesome if this could be fixed. :+1:

**Comment by piannelli** [comment]
Hi,

I don't really have directadmin / cpanel right now. Maybe can any of you guys provide me a tarball, access to a machine or a virtualbox vm to work on it? This will make things much easier :)

**Comment by Wouter0100** [comment]
I'm receiving the following build errors: https://gist.github.com/Wouter0100/859a9a3b7076e72b6972

Yeah, ofcourse. I have a test server here where you should be able to test these things, can you please e-mail me to the e-mailadres provided on my profile? Then I can give you access to the server :+1:. 

(mail mag in het Nederlands verstuurd worden.. ;))

**Comment by piannelli** [comment]
I actually checked it in my local environment and fixed it a bit, but I can see it needs more of my time to fix it entirely. As soon as I get some additional time will try to have it done ;)

**Comment by Wouter0100** [comment]
Awesome! Could you please commit those improvements to this repo? (in a different branch maybe?) That I should be able to take a look too :)

**Comment by piannelli** [comment]
I pushed a version on branch php7. Essentially it works but has some segfault issues that I will have to have a look at

**Comment by Wouter0100** [comment]
Awesome! I will try to install it on our test server, maybe I can fix it. :+1: (No experience with C tho)

**Comment by piannelli** [comment]
Updated and should be fine for now. I disabled the ini_entries_cache usage. This shouldn't be too dramatic in most situations. Perhaps you can test it and let me know if you see any performance issues.

**Comment by Wouter0100** [comment]
Hmm, won't that cause a high I/O usage?

**Comment by piannelli** [comment]
You can always fix it if you got more time than me ;)

**Comment by Wouter0100** [comment]
Hmm, I will try to find an alternative when I have time. No experiance with C tho, but love to learn :+1:

**Comment by RockinRoel** [comment]
Hey, I wrote a patch for the htscanner that's on PECL: https://bugs.php.net/bug.php?id=72269.

It looks to me like the php7 branch has an issue with memory leaks? It looks like strings created with zend_string_init are never released (zend_string_release)? Also, I think that casting zend_string\* to zval\* can't be right?
